Inicial setup "Training maquetado"
wolox-training/mg-react-native pull request #1
Opened 2018-10-18 19:53 UTC by mattgle

## Summary
Initial setup "Training maquetado"

## Trello Card
https://trello.com/c/m64Ng8SZ/11-setup-del-proyecto
## Screenshots
![captura de pantalla 2018-10-18 a la s 16 51 36](https://user-images.githubusercontent.com/44204622/47180124-21767800-d2f6-11e8-8044-4da29ad56681.png)

2018-10-19 12:30 UTC, henryzarza requested changes

2018-10-19 12:30 UTC, henryzarza commented on maquetado/.gitignore
> +.DS_Store
Add a break line

2018-10-19 12:30 UTC, henryzarza commented on maquetado/application.scss
> +  }
Add a break line and the bracket should be aligned.

2018-10-19 12:30 UTC, henryzarza commented on maquetado/application.scss
> +    color: red;
Remember that the indentation should be of 2 spaces. Check this [style guide](https://github.com/Wolox/tech-guides/blob/master/frontend/docs/css-style-guide.md#indentation)

2018-10-19 12:30 UTC, henryzarza commented on maquetado/index.html
> +</html>
Add a break line

2018-10-22 16:04 UTC, henryzarza approved these changes
Good job 👍

2018-10-22 16:39 UTC, SKOLZ approved these changes

2018-10-22 16:43 UTC, merged