Layouts
wolox-training/mg-react-native pull request #8
Opened 2018-10-24 18:05 UTC by mattgle

## Summary
Layouts of technology

## Trello Card
https://trello.com/c/DdWYqZOF/23-content-layout
## Screenshots
![captura de pantalla 2018-10-24 a la s 15 03 42](https://user-images.githubusercontent.com/44204622/47451444-2cba1f80-d79e-11e8-9d2a-57189e638d06.png)

2018-10-24 18:47 UTC, henryzarza requested changes
The design isn't the same of the card

2018-10-24 18:47 UTC, henryzarza commented on maquetado/styles.scss
> +  margin: 10px;
Delete this you should do this with `padding` property. Check this [article](https://medium.com/wolox-driving-innovation/what-margin-padding-taught-me-after-50-projects-6878b53c903f)

2018-10-24 18:47 UTC, henryzarza commented on maquetado/tech.scss
> +  padding: 20px 20px;
You can use the shorthand (`padding: 20px`)

2018-10-24 18:47 UTC, henryzarza commented on maquetado/tech.scss
> +.tech-container {
I think that is necessary that you assign `max-width` and `width` properties

2018-10-24 20:32 UTC, henryzarza approved these changes

2018-10-25 15:26 UTC, SKOLZ requested changes

2018-10-25 15:26 UTC, SKOLZ commented on maquetado/index.html
> +      <img src="assets/angular_icon.svg" alt="react icon" class="tech-icon">
`alt="react icon"` this and all the following tech images are not react icons

2018-10-25 15:26 UTC, SKOLZ commented on maquetado/index.html
>    <h1 class="title">Front-End Tools</h1>
this should be an h2

2018-10-25 15:26 UTC, SKOLZ commented on maquetado/index.html
> +      <h1 class="tech-title">ReactJS</h1>
this should be an h3

2018-10-25 15:26 UTC, SKOLZ commented on maquetado/index.html
> +      <h2 class="tech-release">Release: 2013</h2>
this should be an h4 or a span

2018-10-25 16:24 UTC, SKOLZ approved these changes

2018-10-25 16:24 UTC, merged